export const LOGIN_ROUTE = "/login"
export const REGISTER_ROUTE = "/register"
export const HOME_ROUTE = "/home"
export const PROFILE_ROUTE = "/profile"
export const CALENDAR_ROUTE = "/calendar"
export const REPORT_ROUTE = "/report"